apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - image: nestallum/service1:1
          imagePullPolicy: IfNotPresent
          name: service1
      restartPolicy: Always
